.\" Created from Texinfo source by yat2m 1.0
.TH GPGSM-GENCERT.SH 1 2013-01-27 "GnuPG 2.0.19" "GNU Privacy Guard"
.SH NAME
.B gpgsm-gencert.sh
\- Generate an X.509 certificate request
.SH SYNOPSIS
.B  gpgsm-gencert.sh

.SH DESCRIPTION
This is a simple tool to interactively generate a certificate request
which will be printed to stdout.

.SH SEE ALSO
\fBgpgsm\fR(1),
\fBgpg-agent\fR(1),
\fBscdaemon\fR(1)

The full documentation for this tool is maintained as a Texinfo manual.
If GnuPG and the info program are properly installed at your site, the
command

.RS 2
.nf
info gnupg
.fi
.RE

should give you access to the complete manual including a menu structure
and an index.




